name: 🔒 Lockfile Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # manual trigger for regeneration

jobs:
  check-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: ⚡ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 🔎 Verify lockfile consistency
        run: |
          pnpm install --frozen-lockfile

  regenerate-lockfile:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: ⚡ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 🔄 Rebuild lockfile
        run: |
          rm pnpm-lock.yaml
          pnpm install

      - name: 💾 Commit updated lockfile
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: regenerate pnpm lockfile [ci skip]"
          file_pattern: pnpm-lock.yaml
